# Generated by Django 5.2 on 2025-05-31 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecriturejournal',
            name='compte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptes.compte'),
        ),
        migrations.AddField(
            model_name='ecriturejournal',
            name='nom',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='type',
            field=models.CharField(choices=[('1', 'Journal Achats'), ('2', 'Journal Ventes'), ('3', 'Journal OD'), ('4', 'Banque'), ('5', 'Caisse'), ('6', 'Compte chèques postaux'), ('7', 'Effets à payer'), ('8', 'Effets à recevoir'), ('9', 'Reports à Nouveau'), ('10', 'Journal de clôture'), ('11', 'Journal expert OD'), ('12', 'Journal de réouverture')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Compte',
        ),
    ]
