# Generated by Django 5.2 on 2025-06-03 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('libelle', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('1', 'Journal Achats'), ('2', 'Journal Ventes'), ('3', 'Journal OD'), ('4', 'Banque'), ('5', 'Caisse'), ('6', 'Compte chèques postaux'), ('7', 'Effets à payer'), ('8', 'Effets à recevoir'), ('9', 'Reports à Nouveau'), ('10', 'Journal de clôture'), ('11', 'Journal expert OD'), ('12', 'Journal de réouverture')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EcritureJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('nom', models.CharField(blank=True, max_length=20, null=True)),
                ('libelle', models.CharField(max_length=255)),
                ('quantite', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('taux', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('journal', models.CharField(max_length=10)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptes.comptecomptable')),
            ],
        ),
    ]
