# Generated by Django 5.2 on 2025-06-04 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompteComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('nom', models.CharField(max_length=255)),
                ('type_compte', models.CharField(choices=[('classe1', 'Comptes de capitaux'), ('classe2', 'Immobilisations'), ('classe3', 'Stocks'), ('classe4', 'Tiers'), ('classe5', 'Financiers'), ('classe6', 'Charges'), ('classe7', 'Produits'), ('perso', 'Personnalisé')], default='perso', max_length=20)),
                ('origine', models.CharField(choices=[('pgc', 'PCG'), ('user', 'Utilisateur')], default='pgc', max_length=20)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comptes.comptecomptable')),
            ],
        ),
    ]
