# Generated by Django 5.2 on 2025-05-31 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('libelle', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CreationCompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('numero', models.CharField(max_length=20)),
                ('libelle', models.CharField(max_length=255)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptes.compte')),
            ],
        ),
    ]
